apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pqmx1vokv-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:c1e1557832277c4b1c2615b2193859111947a3aa@sha256:a869034d11b5e8e21c5d217146fdc5f3e6f6684fc9ba330e20cdb4ba3b664d99
          name: container-image
