apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pqmx1vokv-nodejs
  janus-idp.io/tekton: pqmx1vokv-nodejs
  backstage.io/kubernetes-id: pqmx1vokv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pqmx1vokv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
